<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>メモ管理</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="container">
        <h1>メモ管理</h1>
        <div class="memo">
            <div class="memo-body">
                <h2 class="memo-title">メモ一覧</h2>
                <div class="memo-text">
                    <ul class="list-group">
                        <?php foreach($memos as $memo): ?>
                            <li class="list-group-item"><?= htmlspecialchars($memo['subject'],ENT_QUOTES,'UTF-8',false)?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>